version: '3'

services:
  elasticsearch-0: &elasticsearch
    container_name: elasticsearch-0
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: on-failure
    volumes:
      - ./elasticsearch/config/elasticsearch-0.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms512m"
      ELASTIC_PASSWORD: $ELASTIC_PASSWORD
    networks:
      - elk

  elasticsearch-1:
    <<: *elasticsearch
    container_name: elasticsearch-1
    volumes:
      - ./elasticsearch/config/elasticsearch-1.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9201:9200"
      - "9301:9300"

  elasticsearch-2:
    <<: *elasticsearch
    container_name: elasticsearch-2
    volumes:
      - ./elasticsearch/config/elasticsearch-2.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9202:9200"
      - "9302:9300"

  logstash:
    container_name: logstash
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: on-failure
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "9600:9600"
      - "8080:8080"
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch-1

  kibana:
    container_name: kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: on-failure
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch-0
      - elasticsearch-1
      - elasticsearch-2

networks:
  elk:
    driver: bridge
