apm-server:
  host: "0.0.0.0:8200"
  rum:
    enabled: true
  kibana:
    enabled: true
    host: kibana:5601
    username: "${ES_USERNAME}"
    password: "${ES_PASSWORD}"

setup:
  kibana:
    host: kibana:5601
  template:
    settings:
      index:
        number_of_replicas: 0

output.elasticsearch:
  hosts: ${ES_HOSTS}
  username: "${ES_USERNAME}"
  password: "${ES_PASSWORD}"