server.name: kibana
server.host: "0"
elasticsearch.hosts: ${ES_HOSTS}
elasticsearch.username: "${ES_USERNAME}"
elasticsearch.password: "${ES_PASSWORD}"
xpack.monitoring.ui.container.elasticsearch.enabled: true